development:
  secret_key_base: da2dc9f74353e86b86d040d66316a025d4bcce3d19d7b5d6edf94b926f6ba32311b3b093af5646af1dbf1787451b019142919ebd6975058e63648960588b5cb6

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>